export enum ActionTypes {
	FETCH_SONG = 'FETCH SONG',
	UPDATE_SONG_INFO = 'UPDATE INFO',
	ADD_SONG_PART = 'ADD SONG PART',
	DEL_SONG_PART = 'DELETE SONG PART',
	DUPLICATE_SONG_PART = 'DUPLICATE SONG PART',
	ORDER_SONG_PART = 'ORDER SONG PART',
	UPDATE_PART_TYPE = 'UPDATE PART TYPE',
	ADD_PART_LINE = 'ADD PART LINE',
	DEL_PART_LINE = 'DELETE PART LINE',
	UPDATE_TEXT_LINE = 'UPDATE TEXT LINE',
	ADD_CHORD = 'ADD CHORD',
	DEL_CHORD = 'DEL CHORD',
	UPDATE_CHORD = 'UPDATE CHORD'
}

export default ActionTypes;